### ISSUE TITLE
modifying AMP logo

### ISSUE THREAD

**Issue by jaygray0919** [JayHoltslander/Animated-SVG-in-AMP#1]
Would like to modify your AMP logo for different letters in an alternate logo.
But I cannot replace your 'letters' (paths) with new letters.
When I look at your paths more closely, it appears to me that the letters are positioned at a specific location; meaning that 'A' is coded to the left of 'M' and 'P' is coded to the right of 'M'.
Am I interpreting the design correctly?
Can you suggest a method to move a given letter (say, a string of 5 letters) to a specific position?

**Comment by JayHoltslander** [comment]
I'd recommend using the same tool I did to create it. (https://www.keyshapeapp.com/)
Beyond that I don't have any recommendations for editing svg animations I'm afraid.
